[package]
name = "fast-aes-break"
version = "0.1.0"
edition = "2021"

[dependencies]
hdf5 = { version = "0.8.1" }
hdf5-sys = { version = "0.8.1", features = ["static"] }
libc = "0.2.171"
ndarray = "0.15.6"
